name: openhsi_dev
channels:
  - fastai
  - conda-forge
  - nodefaults
dependencies:
  - python==3.8.15
  - numpy
  - pandas
  - scipy
  - matplotlib
  - fastai::nbdev
  - fastai::fastcore 
  - fastai::fastprogress
  - h5py
  - xarray==2022.3.0
  - pillow
  - pandas
  - tqdm
  - bokeh
  - holoviews
  - panel
  - param 
  - pyserial
  - netcdf4
  - Py6S
  - hvplot
  - streamz
  - datashader
  - psutil
  - pre-commit
  - jupyterlab